#!/bin/bash

# Array of folder names
folders=("bin" "nodehomedirectory" "transactions" "wallets")

# Create folders
for folder in "${folders[@]}"
do
    mkdir "$folder"
    if [ $? -eq 0 ]; then
        echo "Folder '$folder' created successfully."
    else
        echo "Failed to create folder '$folder'."
    fi
done